### PR TITLE
Proposed pull request template

### PR DESCRIPTION
**Pull request by wpscholar**
The following is the proposed global pull request template. Please review and suggest any changes.

### CODE REVIEW

**Review by ianbelanger79 — APPROVED** [review]
LGTM 👍

**Review by earnjam — CHANGES_REQUESTED** [review]
What do you think about wrapping the instruction paragraphs in HTML comments? This makes it so the user still sees them inside the textarea field when they go to open an issue, but if they don't delete the paragraph and just add their information below it, it won't display in the issue once submitted and clutter it up. 

The Gutenberg issue template is a good example of this: https://github.com/WordPress/gutenberg/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by wpscholar** [comment]
@earnjam I really like that idea...

**Review by earnjam — APPROVED** [review]
Looks good!

**Review by desrosj — APPROVED** [review]
Looks good to me!

**Pull request merged**
